### ISSUE TITLE
Unable to Log-In on the Website : https://frontend-sih-swart.vercel.app

### ISSUE THREAD

**Issue by Namratha2604** [25sudharsan27/SIH#31]
I am encountering an issue on the website where I am unable to log in. When I click the "Login" button, the page does not redirect or change, and I remain on the login/signup page.

Steps to reproduce:

Go to the login/signup page.
Enter login credentials.
Click the "Login" button.

Expected behavior:

I should be redirected to the dashboard or the appropriate logged-in area.

Actual behavior:

The page stays on the login/signup screen, and no error message is displayed.
Please investigate this issue. Thank you!

**Comment by 25sudharsan27** [comment]
Hi Namratha,

Thank you for bringing this issue to our attention! We appreciate your diligence in helping us improve our website.

I understand the problem you’ve encountered with the login and signup process. I’ve made some changes to the login and signup page to enhance the user experience. Now, when you click the "Login" button, a loading symbol will appear while we process your credentials. If the login is successful, you will be redirected to your profile. If there’s an error with your ID or password, you’ll receive instant pop up to let you know.

Please give it another try and let us know if you encounter any further issues. Your feedback is invaluable!

Best regards,
Sudharsan B,

![image](https://github.com/user-attachments/assets/405ea019-6f01-4bcb-8858-cade74e955c3)
![image](https://github.com/user-attachments/assets/5ae2085b-0992-43bb-947e-780a0299d891)
